const xlsx = require('xlsx');

// JSON data for Praise Songs
const praiseSongs = [
  { title: 'Aaj Ka Yeh Din', youtubeId: 'X7NPwFVgZSY' },
  { title: 'All Things Are Possible', youtubeId: 'EqYBXFYYsxc' },
  { title: 'Be Bold, Be Strong', youtubeId: 'x9Bgxzk_P8w' },
  { title: 'The Name of the Lord', youtubeId: 'bYrcrP1ysjw' },
  { title: 'Build Your Kingdom Here', youtubeId: 'r-4bEbk1m_c' },
  { title: 'Chillakar Gaoonga', youtubeId: 'W7IqTmN11Gw' },
  { title: 'Dancing Generation', youtubeId: '6P2A1VUZYss' },
  { title: 'Everything That Has Breath', youtubeId: 'Iq_Q9Y6zDWs' },
  { title: 'Fear Not for I Am with You', youtubeId: 'FwWPL8iPB64' },
  { title: 'Flames', youtubeId: 'ad__P5ar8G8' },
  { title: 'Forever (Give Thanks to the Lord)', youtubeId: 'vziQffpVZ24' },
  { title: 'Glorious Day', youtubeId: 'LfzpfqrPUDo' },
  { title: 'God is Great', youtubeId: '2SHhpBVuxl0' },
  { title: 'Happy Day', youtubeId: 'vlWPGWfIvwU' },
  { title: 'I Am Free', youtubeId: 'pbO4D9cRFCo' },
  { title: 'I Believe', youtubeId: '1USWVZjTRw8' },
  { title: 'I Belong to Jesus', youtubeId: 'igbTZxbUc5o' },
  { title: "It's All About You", youtubeId: 'ArLrkBgrhmw' },
  { title: 'Jalali Yesu', youtubeId: 'dRcxL_4R7P8' },
  { title: 'Jashn Manaoonga', youtubeId: 'E6NHXIPBLqI' },
  { title: 'King of Glory - Your Face Outshines', youtubeId: '1Y-TYA7DefI' },
  { title: 'King of Heaven', youtubeId: 'VO76W9Zw0cs' },
  { title: 'King of My Heart, King of My Soul', youtubeId: 'NnH812oh7I0' },
  { title: 'You Are Good', youtubeId: 'Qk6Py5RW2AY' },
  { title: 'Majesty', youtubeId: 'vNjH8QDpBFY' },
  { title: 'My God', youtubeId: '89OPH53Ad0Y' },
  { title: 'My Lighthouse', youtubeId: 'reAlJKv7ptU' },
  { title: 'My Redeemer Lives', youtubeId: '3glYEDzSyok' },
  { title: 'One Way', youtubeId: 'yAJnHGoo44E' },
  { title: 'Praise Adonai', youtubeId: 'XpF7xpd-E-E' },
  { title: 'Praise is Raising', youtubeId: '_6t53HBih1I' },
  { title: 'Rock of Ages', youtubeId: '8_gD5pVhS3k' },
  { title: 'Senao Ka Yahova Hamare Sang Sang Hai', youtubeId: 'Z4x2pkdbwOc' },
  { title: 'Shout of the King (I Give You Praise)', youtubeId: '-qfJ7qBz_co' },
  { title: 'Shouts of Joy and Victory', youtubeId: 'DUOAUwT2lgE' },
  { title: 'Sing and Shout', youtubeId: 'Sw8lQ6dggGQ' },
  { title: 'Take it All', youtubeId: '0cYZOo04oUA' },
  { title: 'Tera Anugrah Kaafi Hai', youtubeId: 'gvGrK7K5w0Y' },
  { title: 'The Lord Reigns', youtubeId: 'xfVZpx3zBgA' },
  { title: 'The Walls Will Come Down', youtubeId: 'PaCThULi2rU' },
  { title: 'This is Amazing Grace', youtubeId: 'XFRjr_x-yxU' },
  { title: 'This Is How We Overcome (You Have Turned My Morning Into Dancing)', youtubeId: 'JdCg8oqMlrQ' },
  { title: 'Today is the Day', youtubeId: 'mGVbFiqAXhY' },
  { title: 'Victorious God', youtubeId: 'ODWo5VdBlhM' },
  { title: 'Walk Walk Walk Walk in the Light', youtubeId: 'JTIw5wddnjg' },
  { title: 'Who is Like the Lord', youtubeId: 'gk6GASkBEUQ' },
  { title: 'Yeshu Hai Sacha Gadariya', youtubeId: 'KwHzHS1wy2I' },
  { title: 'Yeshu Vijayi Hai', youtubeId: '-KVeUtI0OEg' },
  { title: 'Yeshua is Lord', youtubeId: '4slU_JjdhrU' },
  { title: 'Your Grace is Enough', youtubeId: 'd7dW6d2-6B0' },
  { title: 'Every Praise', youtubeId: 'VlJIMgh6Oec' },
  { title: 'Trading my sorrows', youtubeId: '2KsfwvpcQhY' },
  { title: 'King of Majesty', youtubeId: 'BI3myzs_k3c' },
  { title: '10000 Armies', youtubeId: '7nxmJY-UghM' },
  { title: 'Praise', youtubeId: 'f2oxGYpuLkw' },
];

// JSON data for Transitional Songs
const transitionSongs = [
  { title: 'Your Grace is Enough', youtubeId: 'd7dW6d2-6B0' },
  { title: "For All You've Done - Hillsong", youtubeId: 'XTlHrmNAMQk' },
  { title: 'Amazing Love', youtubeId: 'SbN_r_6aNq0' },
  { title: 'Arise', youtubeId: 'rG6583arkmw' },
  { title: 'Ascribe Greatness to Our God', youtubeId: '02D3SMB21BI' },
  { title: 'Because He Lives', youtubeId: 'RFIr8-gH55E' },
  { title: 'Better is One Day in Your Courts', youtubeId: 'W4Fj9bbEmVk' },
  { title: 'Blessed Be Your Name', youtubeId: '6AB3ku_c7Dw' },
  { title: 'Break Every Chain', youtubeId: 'ucY6NwQTI3M' },
  { title: 'Come Let Us Worship and Bow Down', youtubeId: 'NEK9u51ofZE' },
  { title: 'Control', youtubeId: 'VghvmL0G144' },
  { title: 'Cornerstone', youtubeId: 'izrk-erhDdk' },
  { title: 'Days of Elijah', youtubeId: 'ca9LnzJnpjQ' },
  { title: 'Worship You for Who You Are - Hillsong', youtubeId: 'bjxkxJnases' },
  { title: 'Everlasting God', youtubeId: 'JSHRThrP1O0' },
  { title: "For All You've Done", youtubeId: 'XTlHrmNAMQk' },
  { title: 'God My Rock', youtubeId: 'bavQSfhLHhc' },
  { title: 'God of This City', youtubeId: 'cEFGr1S8SkA' },
  { title: 'God of Wonders', youtubeId: 'r9orlWiaDfM' },
  { title: 'Hallelujah to My King', youtubeId: 'vdZ5tUHrj_Q' },
  { title: 'He Walked Where I Walk', youtubeId: 'jz2TuUOl8kk' },
  { title: 'Holy is the Lord', youtubeId: 'hVWBt8bfmCs' },
  { title: 'How Great Thou Art', youtubeId: 'p-hvI1nbS80' },
  { title: 'Hosanna in the Highest', youtubeId: 'hnMevXQutyE' },
  { title: 'How Great is Our God', youtubeId: 'XV4nOVmWW2A' },
  { title: 'Hum Gaaye Hosanna', youtubeId: 'vYFxLu5o1Ig' },
  { title: 'Lion and the Lamb', youtubeId: 'q1SXPODm0uE' },
  { title: 'I Can Only Imagine', youtubeId: 'ZNDEyxEMNp0' },
  { title: 'I Will Follow', youtubeId: 'mFna4pEF7M8' },
  { title: 'For Who You Are', youtubeId: 'bjxkxJnases' },
  { title: 'Everlasting God - Lincoln Brewster', youtubeId: 'jP2nz6PG8KM' },
  { title: 'Indescribable God', youtubeId: '5IlVfkY5q54' },
  { title: 'Like a Fire', youtubeId: 'aQx5E7OG3YU' },
  { title: 'Mighty to Save', youtubeId: 'GEAcs2B-kNc' },
  { title: 'Never Let Go', youtubeId: 'J_n4Ysi5iUM' },
  { title: 'No One Like Jehovah', youtubeId: 'KFi6TobuVOg' },
  { title: 'O Come Let Us Adore Him', youtubeId: 'pIj6wtHN21s' },
  { title: 'Our God - Water You Turn Into Wine', youtubeId: 'NJpt1hSYf2o' },
  { title: "Refiner's Fire", youtubeId: 'idA6fCAHVzs' },
  { title: 'See His Love', youtubeId: 'OUKbVuIdDSw' },
  { title: 'Songs in The Night', youtubeId: 'TfkpzWwsJp8' },
  { title: 'Stronger', youtubeId: 'PsO6ZnUZI0g' },
  { title: 'The Battle Belongs to the Lord', youtubeId: 'johgSkNj3-A' },
  { title: 'Who Am I', youtubeId: 'mBcqria2wmg' },
  { title: 'Whom Shall I Fear', youtubeId: 'qOkImV2cJDg' },
  { title: 'Wonderful So Wonderful (Beautiful One)', youtubeId: '5LH9ztB-QDA' },
  { title: 'You Are God Alone (Unstoppable)', youtubeId: 'QLE71ay81tE' },
  { title: 'Prince of Peace', youtubeId: 'pnlg3zfTXZE' },
  { title: 'You Never Let Go', youtubeId: 'PgM-NIPev2w' },
  { title: 'Your Love is Amazing Steady and Unchanging', youtubeId: 'pWT3Hd6WqE0' },
  { title: 'You are worthy of my praise', youtubeId: 'bktcek7iNvE' },
  { title: 'Touch of Heaven', youtubeId: 'sWwHBZm3HIA' },
  { title: 'Give us your heart', youtubeId: 'gLYV43SBARg' },
  { title: 'Easy', youtubeId: 'sa93t5kmoUQ' },
];

// JSON data for Worship Songs
const worshipSongs = [
  { title: 'Enter the holy of holies - Paul Wilbur', youtubeId: 's4CRvAPzxjI' },
  { title: 'Spirit of the Sovereign Lord - Paul Wilbur', youtubeId: '1YAwH75vLl4' },
  { title: 'Kadosh - Paul Wilbur', youtubeId: 'bSMDz1fpHxE' },
  { title: 'Take me in - Petra / Kutless', youtubeId: 'y1vJrX976kQ' },
  { title: 'Cornerstone - Hillsong', youtubeId: 'izrk-erhDdk' },
  { title: 'Aasma se bhi - Anil Kant', youtubeId: '3Er1Qw8zbnc' },
  { title: 'Above All - Hillsong', youtubeId: '5_cxhf5ISeg' },
  { title: 'Agnus Dei', youtubeId: 'har4itYxlBg' },
  { title: 'All to Jesus I Surrender', youtubeId: 'SW8EA7DEQ2M' },
  { title: 'As the deer pants for', youtubeId: 'FBppKZ0eJlQ' },
  { title: 'Aradhana hum karte hai', youtubeId: 'X8Gg_qGdPso' },
  { title: 'Amazing Grace (My Chains are gone)', youtubeId: 'Y-4NFvI5U9w' },
  { title: 'Blessing and honor, Your Name', youtubeId: '1tkxGW1w_Nk' },
  { title: 'Broken Vessels', youtubeId: 'uz9xKtRhpjc' },
  { title: 'Create in me a new heart', youtubeId: 'b7Hk3WFUMvo' },
  { title: 'Crown Him with many crowns', youtubeId: 'YuMh_ept-Js' },
  { title: 'Father God I wonder how I managed to exist', youtubeId: 'nPT8tzdC_sw' },
  { title: 'Your Grace is Enough', youtubeId: 'YvIB_veig5s' },
  { title: 'Glory to Him who has saved us', youtubeId: '65P4SVAqRP4' },
  { title: 'Heart of Worship', youtubeId: 'OD4tB1o6YLw' },
  { title: 'Good good Father', youtubeId: 'CqybaIesbuA' },
  { title: 'Healing is here', youtubeId: 'UFSVWeCe-R4' },
  { title: 'Here I am (Majesty)', youtubeId: 'vNjH8QDpBFY' },
  { title: 'Lovely Lord', youtubeId: '_jIjBuuA87E' },
  { title: 'Here I am to worship', youtubeId: '6CKCThJB5w0' },
  { title: 'Here in Your presence', youtubeId: 'jkkWOUZNI0U' },
  { title: 'I Surrender', youtubeId: 's7jXASBWwwI' },
  { title: 'We will worship the lamb of glory - DENNIS JERNIGAN', youtubeId: '0qXPKITolQU' },
  { title: 'We will worship the lamb of glory', youtubeId: 'qmzwFA2TwUk' },
  { title: 'In Christ alone', youtubeId: 'rn9-UNer6MQ' },
  { title: 'No longer slaves', youtubeId: 'f8TkUMJtK5k' },
  { title: 'Oceans', youtubeId: 'OP-00EwLdiU' },
  { title: 'Once Again', youtubeId: 'zinU3nPNxC8' },
  { title: 'Our God is an awesome God', youtubeId: 'PP9BjKnDaFk' },
  { title: 'Rescue', youtubeId: 'gYR0xP1j4PY' },
  { title: 'Shout to the Lord (My Jesus, My Savior)', youtubeId: '5_aIauL2xKA' },
  { title: 'Shukriya', youtubeId: 'bZUZSLYxK5A' },
  { title: 'Sings my Soul', youtubeId: '5TQWX_EOR_g' },
  { title: 'Take Me into the Holy of Holies', youtubeId: 'JuziDS_4EBI' },
  { title: 'Tere paas aata hu Yeshu Tere paas', youtubeId: 'p4waaA11CcA' },
  { title: "Victor's Crown", youtubeId: '_2nBOGA6X2g' },
  { title: 'We fall down we lay our crowns', youtubeId: '7Ge9O_HOKcE' },
  { title: 'Yeshu Masih Tere Jaisa hai koi nahi', youtubeId: '82MsQth2kPk' },
  { title: 'Yeshu Naam Yeshu Naam', youtubeId: '8Y2XpaX3aX0' },
  { title: 'You Alone Are Worthy', youtubeId: 'yb9sE07i7kw' },
  { title: 'You are Beautiful', youtubeId: 'oofSnsGkops' },
  { title: 'You Deserve the Glory and the Honor', youtubeId: 'Asvp4ysmhVE' },
  { title: 'For Your name is holy - Paul Wilbur', youtubeId: 's4CRvAPzxjI' },
  { title: 'Breath', youtubeId: 'KqNeIqvpdjw' },
  { title: 'What love, my God', youtubeId: 'CjXK9PdCpis' },
  { title: 'Oh The Cross', youtubeId: 'HyR_Pnggv_A' },
  { title: 'Boldly I Approach', youtubeId: 'Xx94Fg4qZr8' },
  { title: 'When Wind Meets Fire', youtubeId: '7Q5d6zvf8Q' },
  { title: 'Been So Good', youtubeId: 'D3yMC_qoAes' },
];

// Function to convert JSON arrays to an Excel file with separate sheets
function convertJsonToExcel() {
  // Create a new workbook
  const workbook = xlsx.utils.book_new();

  // Convert each JSON array into a sheet
  const praiseSheet = xlsx.utils.json_to_sheet(praiseSongs);
  const transitionSheet = xlsx.utils.json_to_sheet(transitionSongs);
  const worshipSheet = xlsx.utils.json_to_sheet(worshipSongs);

  // Append the sheets to the workbook
  xlsx.utils.book_append_sheet(workbook, praiseSheet, 'Praise Songs');
  xlsx.utils.book_append_sheet(workbook, transitionSheet, 'Transitional Songs');
  xlsx.utils.book_append_sheet(workbook, worshipSheet, 'Worship Songs');

  // Write the workbook to a file
  xlsx.writeFile(workbook, 'songs.xlsx');
  console.log('Excel file "songs.xlsx" has been created.');
}

convertJsonToExcel();
